#!/usr/bin/env python3
"""Generate deterministic, representative INT8 weights/biases for the
80-40-20-10-20-40-80 dense autoencoder IDS used by the HIL benchmark.

The VALUES here are placeholders (a fixed PRNG seed) and are clearly marked as
representative.  This is intentional and does NOT affect the validity of the
HIL measurement:  inference latency, RAM and Flash footprint depend ONLY on the
network architecture (layer dimensions) and the quantization scheme (INT8,
symmetric per-tensor, int32 accumulate), NOT on the numeric values of the
weights.  The integer MAC count, memory layout, and instruction stream are
identical for any int8 weight set of these dimensions.  Only the detection F1
score depends on trained weight values, and that comes from the offline
software pipeline, never from the embedded measurement.
"""
import textwrap

# (in_dim, out_dim) for each fully-connected layer
LAYERS = [(80, 40), (40, 20), (20, 10), (10, 20), (20, 40), (40, 80)]

# Simple, fully deterministic 32-bit LCG (Numerical Recipes constants).
_state = 0x12345678
def lcg():
    global _state
    _state = (_state * 1664525 + 1013904223) & 0xFFFFFFFF
    return _state

def rand_w():
    # int8 weight in [-100, 100], symmetric, never -128 (keeps |w| <= 100)
    return (lcg() % 201) - 100

def rand_b():
    # small int32 bias in [-2048, 2047]
    return (lcg() % 4096) - 2048

def fmt_array(name, values, ctype):
    body = ", ".join(str(v) for v in values)
    wrapped = textwrap.fill(body, width=96,
                            initial_indent="    ", subsequent_indent="    ")
    return f"const {ctype} {name}[{len(values)}] = {{\n{wrapped}\n}};\n"

lines = []
lines.append("/* ============================================================================")
lines.append(" *  model_weights.h  --  AUTO-GENERATED. DO NOT EDIT BY HAND.")
lines.append(" *  Generated by hil/tools/gen_weights.py (deterministic LCG, seed 0x12345678).")
lines.append(" *")
lines.append(" *  REPRESENTATIVE INT8 weights/biases for the 80-40-20-10-20-40-80 dense")
lines.append(" *  autoencoder IDS.  Values are placeholders; the trained values live in the")
lines.append(" *  offline software pipeline.  Resource/timing measured on-silicon are")
lines.append(" *  architecture- and quantization-dependent and weight-VALUE-independent, so")
lines.append(" *  the HIL latency/RAM/Flash numbers are valid for ANY int8 weight set of")
lines.append(" *  these dimensions.  Only the detection F1 depends on the actual values.")
lines.append(" * ========================================================================== */")
lines.append("#ifndef MODEL_WEIGHTS_H")
lines.append("#define MODEL_WEIGHTS_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")

total_w = 0
total_b = 0
for i, (din, dout) in enumerate(LAYERS):
    w = [rand_w() for _ in range(din * dout)]   # layout: [out][in]
    b = [rand_b() for _ in range(dout)]
    total_w += len(w)
    total_b += len(b)
    lines.append(f"/* Layer {i}: {din} -> {dout}  (weights laid out as [out_dim][in_dim]) */")
    lines.append(fmt_array(f"ae_w{i}", w, "int8_t"))
    lines.append(fmt_array(f"ae_b{i}", b, "int32_t"))
    lines.append("")

lines.append(f"/* Totals: {total_w} int8 weights ({total_w} bytes Flash),"
             f" {total_b} int32 biases ({total_b*4} bytes Flash). */")
lines.append("#endif /* MODEL_WEIGHTS_H */")

out = "\n".join(lines) + "\n"
with open("D:/clarividence/drafts/submitted/2026-canbus-anomaly-detection-motorcycle/hil/model_weights.h", "w") as f:
    f.write(out)

print(f"weights={total_w} bytes, biases={total_b*4} bytes")
